### ISSUE TITLE
Update Start-Up Screen Logo

### ISSUE THREAD

**Issue by bitcoin3us** [LightningPiggy/lightning-piggy#8]
Suggest updating the startup screen logo with the one Bitko donated. Svg file linked.

![BY_-_Lightning_Piggy_logo](https://github.com/LightningPiggy/lightning-piggy/assets/115934595/a350026b-416a-42fd-80c5-7686ffa15c56)

**Comment by ThomasFarstrike** [comment]
This is done in the updated master branch, version 1.9.6 and beyond.

**Comment by ThomasFarstrike** [comment]
This is ready and deployed in v2.0.0 in the [webinstaller](https://lightningpiggy.github.io/).
